version: "3.8"

services:
  simpleweb:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
    - simpleweb-network
networks:
  simpleweb-network: